### ISSUE TITLE
får null när man trade:ar

### ISSUE THREAD

**Issue by bystam** [bystam/settlers-js#1]
Gjorde:
- 1 spelare
- skaffa 5 resurser (av samma typ)
- lägg alla i trade
- ta bort de två till vänster (tre ska vara kvar i trade panel)
- klicka trade mot något

Hände:
- Någon resurs blir null (refereras det dåligt till en resurs i trade-panel?)

Förväntade:
- Bättre jävla kod, för helvete Jens.

**Comment by jensa** [comment]
Ja, hela korthanteringen suger lite för tillfället - försökte återanvända för mycket kod, slutade med att jag hade en ful coupling som ändå inte löste problemet. Ska tänka om hela resurshanteringen

**Comment by jensa** [comment]
Pushat upp en allmän fix, har lite grejer kvar att fixa:
Kolla att man faktiskt har valt något att trada mot (så man inte får null och kraschar servern)
gör att man kan välja om vad man ska trada mot även innan man tradeat
