### ISSUE TITLE
settlements ritas inte ut för player 2 längre

### ISSUE THREAD

**Issue by bystam** [bystam/settlers-js#2]
gjorde:
- 2 spelare
- starta spelet
- sätt ut allt korrekt som spelare 1
- next turn
- försök sätt ut en settlement
- sätt ut två vägar
- next turn

hände:
- man ser inte sin settlement, men man får resurser för den som om att den vore där

förväntade:
- att man ser sin settlement. har utritningen för player 2 försvunnit?

**Comment by jensa** [comment]
Var relaterat till en annan bugg som gjorde att animationen på end turn fastnade för player 2 - snap.svgs animationer är... lite oförutsägbara.

Fixat i senaste commiten (kan man länka commits i en sån här tråd?)
